### PR TITLE
Change with outlook mailto

### PR DESCRIPTION
**Pull request by danetrata**
A change with the hotmail/outlook mailto broke its service.

### CODE REVIEW

**Comment by Noitidart** [comment]
Thanks very much for this PR! I tried this URL:

`https://outlook.live.com/owa/?&rru=compose&to=mailto:noitidart@gmail.com`

It loads my hotmail account, but then just sit there for liek 10 seconds, then it loads the compose page but with the `mailto` prefix:



This i already much better then before so I would love to accept this however do you know how to get it to strip the mailto: prefix?

**Comment by callmetaste** [comment]
Strange. What line is the `mailto:email` string being formatted? I tried looking for it but can't figure it out. I was thinking along the lines of `str.slice(7)` if outlook. Outlook seems really quirky because the addon works in the other services without issue.

**Comment by Noitidart** [comment]
Whenever we click any `mailto:` link in Firefox it loads the URL with `mailto:` prefix :(

**Comment by callmetaste** [comment]
There's no way to format the string being passed to the template? It seems outlook has made it so it doesn't take `...?mailto:sample@email.com`'s. The `mailto:` piece only seems to work when its in `<a href=mailto:sample@email.com>...</a>` and still only composes with outlook.

**Comment by Noitidart** [comment]
I tried I was not able to format the string :(
I'll try again, but for now I'll merge this PR thanks for it very much!

**Pull request merged**
